from markupsafe import Markup
from odoo import fields, models
from odoo.exceptions import UserError


class AccountMove(models.Model):
    _inherit = 'account.move'

    # ── Snapshot link ─────────────────────────────────────────────────────────
    component_snapshot_ids = fields.One2many(
        comodel_name='sale.invoice.component.snapshot',
        inverse_name='invoice_id',
        string='Component Snapshots',
        copy=False,
    )

    # ── Capture snapshot on confirmation ─────────────────────────────────────
    def action_post(self):
        result = super().action_post()
        for move in self.filtered(
            lambda m: m.move_type in ('out_invoice', 'out_refund')
        ):
            # Skip if snapshots were already written (adjustment docs get theirs
            # from _adjust_invoices_for_price_update before posting)
            if move.component_snapshot_ids:
                continue
            # Skip adjustment documents — they don't have sale_line_ids and
            # their snapshots are created at adjustment-document creation time
            is_adjustment = self.env['sale.order'].search_count([
                ('adjustment_invoice_ids', 'in', [move.id])
            ])
            if is_adjustment:
                continue
            move._capture_component_snapshot()
        return result

    def _capture_component_snapshot(self):
        """Capture the current SO line component state as 'normal' snapshots
        on this invoice.  Called when a standard customer invoice is posted."""
        Snapshot = self.env['sale.invoice.component.snapshot'].sudo()
        for move in self:
            so_lines = move.invoice_line_ids.mapped('sale_line_ids').filtered(
                lambda l: l.has_dynamic_components and l.selected_component_ids
            )
            for sol in so_lines:
                for comp in sol.selected_component_ids:
                    Snapshot.create({
                        'invoice_id': move.id,
                        'sale_line_id': sol.id,
                        'product_display_name': sol.product_id.display_name,
                        'component_product_id': comp.component_product_id.id,
                        'group_id': comp.group_id.id if comp.group_id else False,
                        'qty': comp.qty,
                        'uom_id': comp.uom_id.id if comp.uom_id else False,
                        'sale_price': comp.sale_price,
                        'subtotal': comp.subtotal,
                        'notes': comp.notes or '',
                        'snapshot_type': 'normal',
                        'sequence': comp.sequence,
                    })

    # ── Block resetting confirmed dynamic-component invoices to draft ─────────
    def button_draft(self):
        for move in self:
            if move.state != 'posted':
                continue
            if move.move_type not in ('out_invoice', 'out_refund'):
                continue

            # ── Case A: adjustment invoice created by this module ──────────────
            # Resetting it to draft would corrupt the accumulated price history
            # that subsequent Update Price calls rely on.
            adj_orders = self.env['sale.order'].search([
                ('adjustment_invoice_ids', 'in', [move.id])
            ], limit=1)
            if adj_orders:
                raise UserError(
                    'Cannot reset this price adjustment document to draft.\n\n'
                    'This document was automatically generated by the system '
                    'as a price adjustment. Resetting it to draft would '
                    'corrupt the accumulated price history used by future '
                    'component updates.\n\n'
                    'If you need to modify the adjustment, delete this '
                    'document and click "Update Price" on the sale order '
                    'line to regenerate it.'
                )

            # ── Case B: original invoice with dynamic components + active MO ──
            if not move.component_snapshot_ids.filtered(
                lambda s: s.snapshot_type == 'normal'
            ):
                continue
            so_lines = move.invoice_line_ids.mapped('sale_line_ids').filtered(
                lambda l: l.has_dynamic_components
            )
            for sol in so_lines:
                active_mo = self.env['mrp.production'].search([
                    ('is_dynamic_bom', '=', True),
                    ('dynamic_sale_line_id', '=', sol.id),
                    ('state', 'not in', ['cancel', 'done']),
                ], limit=1)
                if active_mo:
                    raise UserError(
                        'Cannot reset this invoice to draft.\n\n'
                        'A manufacturing order (%s) is active for '
                        'product "%s". Resetting the invoice to draft '
                        'after dynamic components have been configured '
                        'may cause inconsistencies in component snapshots '
                        'and price history.\n\n'
                        'To make corrections, cancel the manufacturing '
                        'order first, or issue a manual price adjustment.'
                        % (active_mo.name, sol.product_id.display_name)
                    )
        return super().button_draft()

    # ── Warn on deletion of draft adjustment docs ─────────────────────────────
    def unlink(self):
        """When a draft adjustment invoice/credit note is deleted,
        post a reminder note on the linked sale order(s)."""
        for move in self:
            if move.state != 'draft':
                continue
            orders = self.env['sale.order'].search([
                ('adjustment_invoice_ids', 'in', move.id),
            ])
            for order in orders:
                adj_lines = move.invoice_line_ids.filtered(
                    lambda l: l.display_type == 'product'
                )
                product_names = ', '.join(
                    l.name for l in adj_lines if l.name
                ) or move.name or ''
                doc_type = 'Credit Note' if move.move_type == 'out_refund' else 'Invoice'
                order.message_post(body=Markup(
                    '⚠️ Draft %s for price adjustment (<b>%s</b>) was deleted. '
                    'Press <b>Update Price</b> on the sale order line to regenerate '
                    'the adjustment document.'
                ) % (doc_type, product_names))
        return super().unlink()
