from odoo import fields, models


class SaleInvoiceComponentSnapshot(models.Model):
    """Stores a point-in-time copy of the dynamic components that were active
    on a Sale Order line at the moment a customer invoice was confirmed, or
    the incremental diff (additions / reductions) when a price-adjustment
    invoice / credit note was generated by the module."""

    _name = 'sale.invoice.component.snapshot'
    _description = 'Dynamic Component Snapshot at Invoice Time'
    _order = 'sale_line_id, sequence, id'

    invoice_id = fields.Many2one(
        'account.move',
        string='Invoice',
        required=True,
        ondelete='cascade',
        index=True,
    )
    sale_line_id = fields.Many2one(
        'sale.order.line',
        string='Sale Order Line',
        ondelete='set null',
        index=True,
    )
    # Captured at snapshot time so we can still display it if the SO line is later deleted
    product_display_name = fields.Char(
        string='Product (SO Line)',
        help='Display name of the main product on the Sale Order line.',
    )
    component_product_id = fields.Many2one(
        'product.product',
        string='Component',
        required=True,
    )
    group_id = fields.Many2one(
        'mrp.component.group',
        string='Group',
    )
    qty = fields.Float(
        string='Quantity',
        digits='Product Unit of Measure',
    )
    uom_id = fields.Many2one('uom.uom', string='UoM')
    packaging_qty = fields.Float(
        string='Packaging Quantity',
        digits='Product Unit of Measure',
        default=1.0,
        help='Number of base units in the packaging at snapshot time.',
    )
    sale_price = fields.Float(string='Unit Price', digits='Product Price')
    subtotal = fields.Float(string='Subtotal', digits='Product Price')
    notes = fields.Text(string='Notes')
    sequence = fields.Integer(string='Sequence', default=10)

    snapshot_type = fields.Selection(
        selection=[
            ('normal',    'Normal — full component list at invoice confirmation'),
            ('addition',  'Addition — component added / qty increased vs. prior invoice'),
            ('reduction', 'Reduction — component removed / qty decreased vs. prior invoice'),
        ],
        string='Snapshot Type',
        default='normal',
        required=True,
    )
    # Datetime of the Update Components/Price action that triggered this snapshot
    update_date = fields.Datetime(
        string='Update Date',
        help='Timestamp of the Update Components / Update Price action that '
             'generated this adjustment snapshot.',
    )
